# Generated file used for preloading a child image
set(CMAKE_BUILD_TYPE "" CACHE INTERNAL "NCS child image controlled")
set(CMAKE_VERBOSE_MAKEFILE "FALSE" CACHE INTERNAL "NCS child image controlled")
set(BOARD_DIR "C:/ncs/v2.9.1/zephyr/boards/nordic/nrf5340dk" CACHE INTERNAL "NCS child image controlled")
set(ZEPHYR_TOOLCHAIN_VARIANT "zephyr" CACHE INTERNAL "NCS child image controlled")
set(CROSS_COMPILE "C:/ncs/toolchains/b620d30767/opt/zephyr-sdk/arm-zephyr-eabi/bin/arm-zephyr-eabi-" CACHE INTERNAL "NCS child image controlled")
set(NCS_TOOLCHAIN_VERSION "NONE" CACHE INTERNAL "NCS child image controlled")
set(PM_DOMAINS "CPUNET" CACHE INTERNAL "NCS child image controlled")
set(CPUNET_PM_DOMAIN_DYNAMIC_PARTITION "hci_ipc" CACHE INTERNAL "NCS child image controlled")
set(WEST_PYTHON "C:/ncs/toolchains/b620d30767/opt/bin/python.exe" CACHE INTERNAL "NCS child image controlled")
set(BOARD_ROOT "c:/users/ralls/github/rarebit-flags-receivers;c:/ncs/v2.9.1/zephyr;c:/users/ralls/github/bluetooth-n64-controller/serial1_periph_blejoybus" CACHE INTERNAL "NCS child image controlled")
set(FILE_SUFFIX "" CACHE INTERNAL "NCS child image controlled")
set(BOARD "nrf5340dk/nrf5340/cpunet" CACHE INTERNAL "NCS child image controlled")
set(DOMAIN "CPUNET" CACHE INTERNAL "NCS child image controlled")
set(EXTRA_CONF_FILE ";C:/ncs/v2.9.1/nrf/subsys/partition_manager/partition_manager_enabled.conf" CACHE INTERNAL "NCS child image controlled")
